import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./variable.css";
import "./globals.css";
import { Header } from "@/component/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          minHeight: "100vh",
          minWidth: "100vw",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
